server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      #      default-filters:
      #        - name: SessionFilter
      #        - name: ThrottlingFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/