package com.productservice.Entity.Enum;


public enum SubCategory {
    //ElectronicsSubCategory
    PHONES_AND_TABLETS,
    COMPUTERS_AND_LAPTOPS,
    TVS_AND_HOME_THEATER_SYSTEMS,
    CAMERAS_AND_PHOTOGRAPHY,
    AUDIO_SYSTEMS_AND_HEADPHONES,
    //FashionSubCategory
    MEN_CLOTHING,
    WOMEN_CLOTHING,
    SHOES_AND_ACCESSORIES,
    KIDS_CLOTHING,
    SPORTS_APPAREL,
    //HomeAndGardenSubCategory
    FURNITURE,
    HOME_DECOR,
    KITCHENWARE,
    GARDEN_AND_OUTDOOR_PRODUCTS,
    HOME_TEXTILES,
    //BeautyAndPersonalCareSubCategory
    MAKEUP_AND_COSMETICS,
    SKIN_CARE,
    HAIR_CARE_AND_ACCESSORIES,
    PERSONAL_HYGIENE_PRODUCTS,
    //SportsAndOutdoorsSubCategory
    SPORTING_GOODS,
    EXERCISE_AND_FITNESS_EQUIPMENT,
    OUTDOOR_ACTIVITY_GEAR,
    CAMPING_EQUIPMENT,
    SPORTSWEAR,
    //ToysAndEntertainmentSubCategory
    GAMING_CONSOLES_AND_ACCESSORIES,
    GAMES_AND_SOFTWARE,
    PUZZLES_AND_GAME_SETS,
    ADULT_ENTERTAINMENT_PRODUCTS,
    PARTY_SUPPLIES,
}
